spring:
  h2:
    console:
      enabled: true
  profiles:
    active: local # 기본 환경 선택
    include: oauth
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL
  session:
    store-type: jdbc
#local
---
spring:
  profiles: local
  jpa:
    show-sql: true